In [1]:
pylab inline

Populating the interactive namespace from numpy and matplotlib


In [7]:
eig([[-2,2],[2,-2]])

(array([  4.44089210e-16,  -4.00000000e+00]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [8]:
a,b,c=svd([[-2,2],[2,-2]])

In [9]:
a,b,c

(array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]),
 array([ 4.,  0.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [10]:
dot(c,a)

array([[ -1.00000000e+00,   1.11022302e-16],
       [  2.22044605e-16,   1.00000000e+00]])

In [5]:
? svd

In [14]:
a,b=eig(dot([[1,0],[0,2]],[[-1,1],[1,-1]]))

In [16]:
dot(b,b.T)


array([[ 0.7,  0.1],
       [ 0.1,  1.3]])

In [17]:
dot(b.T,b)

array([[ 1.        ,  0.31622777],
       [ 0.31622777,  1.        ]])